<?xml version='1.0' encoding='UTF-8' ?><!--
Created by Alight Motion (http://alightmotion.com)
Exported: 2024-12-19 09:00 AM
5.0.270.1002578 (1002351)
6dff462 (Apr 11, 2024 6:17:55 PM)
-->
<scene title="3D Text Pack 10k&#128315;" width="1080" height="1080" exportWidth="1080" exportHeight="1080" precompose="dynamicResolution" bgcolor="#ff000000" totalTime="9265" fps="30" modifiedTime="1734579025859" amver="1002351" ffver="106" am="com.alightcreative.motion/5.0.270.1002578" amplatform="android" retime="freeze" retimeAdaptFPS="false">
  <bookmark t="2016" />
  <bookmark t="4016" />
  <bookmark t="5516" />
  <bookmark t="7483" />
  <shape id="10068706" label="Rounded Rectangle 1" startTime="0" endTime="9265" fillType="gradient" mediaFillMode="fill" s=".roundrect">
    <transform>
      <location value="540.000000,675.000000,0.000000" />
      <scale value="5.400000,6.750000" />
    </transform>
    <fillColor value="#ffe0cae3" />
    <gradient type="linear" startColor="#ff000000" endColor="#ff444444" start="0.499482,0.906563" end="0.498689,-0.242911" />
    <property name="size" type="vec2" value="100.000000,100.000000" />
    <property name="cornerRadius" type="float" value="0.000000" />
  </shape>
  <shape id="10068707" label="Snow Overlay.mp4" startTime="0" endTime="9265" fillType="media" blending="lighten" fillVideo="content://media/external/video/media/1048117" outTime="9265" mediaFillMode="fill" s=".rect">
    <transform>
      <location value="540.000000,675.000000,0.000000" />
      <scale value="2.224053,2.224053" />
    </transform>
    <property name="size" type="vec2" value="540.000000,303.500000" />
  </shape>
  <text id="10068697" label="NAH I'D WIN " startTime="0" endTime="2032" fillType="color" speed="0.500000" mediaFillMode="stretch" size="24.000000" font="imported?name=Lemon Milk Pro Bold.otf" wrapWidth="1414" align="center">
    <transform>
      <location value="540.000000,542.265137,0.000000" />
      <scale>
        <kf t="4.847443" v="2.081330,2.081330" e="cubicBezier 0.23919915 0.7721349 0.67259413 0.8487826" />
        <kf t="0.992126" v="1.649222,1.649222" e="cubicBezier 0.1 0.36 0.34 0.87" />
        <kf t="0.000000" v="0.848656,0.848656" />
      </scale>
    </transform>
    <fillColor value="#ffff0000" />
    <gradient type="linear" startColor="#ff444444" endColor="#ffffffff" start="0.500454,0.970873" end="0.493246,0.147624" />
    <effect id="com.alightcreative.effects.extrudepoint" locallyApplied="true">
      <property name="orient" type="quat">
        <kf t="0.007873" v="0.920505,0.000000,0.000000,0.390731" />
        <kf t="1.565944" v="-0.147809,-0.000000,0.000000,0.989016" e="cubicBezier 0.03938423 0.8744456 0.33236867 1.0" />
      </property>
      <property name="rotate" type="vec3" value="-6.000000,0.000000,0.000000" />
      <property name="position" type="vec3" value="0.000000,100.000000,500.000000" />
      <property name="stretch" type="vec2" value="1.000000,1.000000" />
      <property name="depth" type="float" value="0.017000" />
      <property name="scale" type="float" value="1.000000" />
      <property name="lightIntensity" type="float" value="1.047000" />
      <property name="shine" type="float" value="0.800000" />
      <property name="spec" type="float" value="48.000000" />
      <property name="ambient" type="float" value="0.100000" />
      <property name="lightColor" type="color" value="#ffffffff" />
      <property name="lightDir" type="vec2" value="75.000000,-75.000000" />
      <property name="lightDepth" type="float" value="100.000000" />
      <property name="MAX_ITER" type="float" value="300.000000" />
      <property name="inton" type="bool" value="false" />
      <property name="interiorColor" type="color" value="#ff000000" />
      <property name="interiorBlend" type="float" value="1.000000" />
      <property name="fadeColor" type="color" value="#ffff4444" />
      <property name="fadeBlend" type="float" value="0.330000" />
    </effect>
    <effect id="com.alightcreative.internal.smoothbevel" locallyApplied="true">
      <property name="angle_d" type="float" value="0.000000" />
      <property name="angle_s" type="float" value="0.000000" />
      <property name="intensity_d" type="float" value="0.000000" />
      <property name="radius" type="float" value="6.000000" />
      <property name="color_d" type="color" value="#ffffffff" />
      <property name="color_s" type="color" value="#ffffffff" />
      <property name="intensity_s" type="float" value="1.000000" />
      <property name="elevation_d" type="float" value="0.000000" />
      <property name="elevation_s" type="float" value="2.200000" />
      <property name="spec" type="float" value="35.000000" />
    </effect>
    <effect id="com.alightcreative.effects.paperburn" locallyApplied="true">
      <property name="color" type="color" value="#ffff4444" />
      <property name="progressa" type="float">
        <kf t="0.007873" v="0.140000" />
        <kf t="0.187994" v="0.200000" />
        <kf t="0.483268" v="0.110000" />
        <kf t="0.844488" v="0.190000" />
        <kf t="1.713583" v="0.280000" />
        <kf t="2.058071" v="0.190000" />
        <kf t="2.566931" v="0.280000" />
        <kf t="2.894686" v="0.200000" />
        <kf t="3.255906" v="0.310000" />
        <kf t="3.534448" v="0.170000" />
        <kf t="3.944882" v="0.290000" />
        <kf t="4.387795" v="0.170000" />
        <kf t="4.847443" v="0.260000" />
      </property>
      <property name="feather" type="float">
        <kf t="0.000000" v="11.500000" />
      </property>
      <property name="alpha" type="float" value="1.000000" />
    </effect>
    <effect id="com.alightcreative.effects.motionblur4" locallyApplied="true">
      <property name="tune" type="float" value="1.000000" />
      <property name="usePos" type="bool" value="true" />
      <property name="useScale" type="bool" value="true" />
      <property name="useAngle" type="bool" value="true" />
    </effect>
    <effect id="com.alightcreative.effects.textspacing" locallyApplied="true">
      <property name="letterspacing" type="float" value="0.050000" />
      <property name="linespacing" type="float" value="1.000000" />
    </effect>
    <effect id="com.alightcreative.effects.edgeglow" locallyApplied="true">
      <property name="smoothing" type="float" value="3.000000" />
      <property name="threshold" type="float" value="1.000000" />
      <property name="invert" type="bool" value="false" />
      <property name="strength" type="float" value="0.100000" />
      <property name="spread" type="float" value="1.500000" />
      <property name="fillColor" type="color" value="#ff0088ff" />
      <property name="blend" type="float" value="0.000000" />
      <property name="gamma" type="float" value="1.000000" />
      <property name="brightness" type="float" value="0.000000" />
      <property name="tintColor" type="color" value="#ff000000" />
      <property name="tint" type="float" value="0.000000" />
    </effect>
    <effect id="com.alightcreative.effects.edgeglow" locallyApplied="true">
      <property name="smoothing" type="float" value="3.000000" />
      <property name="strength" type="float" value="0.670000" />
      <property name="threshold" type="float" value="1.000000" />
      <property name="invert" type="bool" value="false" />
      <property name="spread" type="float" value="1.500000" />
      <property name="fillColor" type="color" value="#ff0088ff" />
      <property name="blend" type="float" value="0.000000" />
      <property name="gamma" type="float" value="1.000000" />
      <property name="brightness" type="float" value="0.000000" />
      <property name="tintColor" type="color" value="#ff000000" />
      <property name="tint" type="float" value="0.000000" />
    </effect>
    <effect id="com.alightcreative.effects.rays" locallyApplied="true">
      <property name="centerPoint" type="vec2" value="9.000000,0.000000" />
      <property name="strength" type="float" value="1.280000" />
      <property name="intensity" type="float" value="1.000000" />
      <property name="threshold" type="float" value="0.980000" />
      <property name="thresholdColor" type="color" value="#ff000000" />
      <property name="fillColor" type="color" value="#ff2d1ef6" />
      <property name="blend" type="float" value="0.000000" />
      <property name="quality" type="float" value="150.000000" />
    </effect>
    <path-stroke direction="centered" end-size="1.500000">
      <color value="#ffffffff" />
    </path-stroke>
    <shadow direction="outside">
      <size value="12.000000" />
      <offset value="12.000000,5.000000" />
    </shadow>
    <content>DOES IT</content>
  </text>
  <embedScene id="10068699" startTime="2033" endTime="4032" fillType="intrinsic" outTime="1865" speed="0.932880" mediaFillMode="stretch">
    <transform>
      <location value="592.889343,519.953247,0.000000" />
      <scale value="1.111583,1.111583" />
    </transform>
    <fillColor value="#ff000000" />
    <effect id="com.alightcreative.effects.brightcont2" locallyApplied="false">
      <property name="brightness" type="float" value="-0.100000" />
      <property name="contrast" type="float" value="0.100000" />
    </effect>
    <effect id="com.alightcreative.effects.rays" locallyApplied="false">
      <property name="intensity" type="float" value="1.140000" />
      <property name="strength" type="float" value="0.590000" />
      <property name="threshold" type="float" value="0.500000" />
      <property name="thresholdColor" type="color" value="#ff000000" />
      <property name="fillColor" type="color" value="#ff2d1ef6" />
      <property name="blend" type="float" value="0.000000" />
      <property name="quality" type="float" value="145.000000" />
      <property name="centerPoint" type="vec2" value="-18.000000,0.000000" />
    </effect>
    <scene title="" width="1282" height="722" exportWidth="1920" exportHeight="1080" precompose="dynamicResolution" bgcolor="#00000000" totalTime="75865" fps="60" modifiedTime="0" amver="1002351" ffver="106" am="com.alightcreative.motion/5.0.270.1002578" amplatform="android" retime="off" retimeAdaptFPS="false">
      <bookmark t="15091" />
      <embedScene id="370163" label="Group 1" startTime="0" endTime="75865" fillType="intrinsic" outTime="75865" mediaFillMode="stretch">
        <transform>
          <location value="506.034851,382.325195,0.000000" />
          <pivot value="-145.703125,0.000000" />
        </transform>
        <fillColor value="#ff000000" />
        <scene title="" width="1282" height="722" exportWidth="1920" exportHeight="1080" precompose="dynamicResolution" bgcolor="#00000000" totalTime="33843" fps="60" modifiedTime="0" amver="1002351" ffver="106" am="com.alightcreative.motion/5.0.270.1002578" amplatform="android" retime="off" retimeAdaptFPS="false">
          <text id="370161" startTime="0" endTime="33843" fillType="color" mediaFillMode="stretch" size="56.000000" font="imported?name=Montserrat-Bold.ttf" wrapWidth="260" align="center">
            <transform>
              <location value="494.296875,360.000000,0.000000" />
              <rotation>
                <kf t="0.000000" v="0.000000" />
              </rotation>
            </transform>
            <fillColor value="#ff7f7f7f" />
            <effect id="com.alightcreative.effects.flip3" locallyApplied="false">
              <property name="angle" type="float">
                <kf t="0.000000" v="48.100002" />
                <kf t="0.059333" v="10.900001" />
              </property>
              <property name="axis" type="float" value="37.000000" />
              <property name="crop" type="float" value="1.000000" />
              <property name="zdist" type="float" value="0.000000" />
              <property name="solid" type="bool" value="false" />
              <property name="solidColor" type="color" value="#ffdd4455" />
              <property name="thickness" type="float" value="1.000000" />
              <property name="enableLight" type="bool" value="false" />
              <property name="lightIntensity" type="float" value="1.000000" />
              <property name="lightColor" type="color" value="#ffffffff" />
              <property name="shine" type="float" value="0.800000" />
              <property name="spec" type="float" value="30.000000" />
              <property name="ambient" type="float" value="0.100000" />
              <property name="lightDir" type="vec2" value="75.000000,-75.000000" />
              <property name="lightDepth" type="float" value="-100.000000" />
            </effect>
            <effect id="com.alightcreative.effects.longshadow2" locallyApplied="false">
              <property name="alpha" type="float" value="1.000000" />
              <property name="angle" type="float" value="326.500000" />
              <property name="size" type="float">
                <kf t="0.000000" v="0.034000" />
                <kf t="0.059540" v="0.012000" />
              </property>
              <property name="color" type="color" value="#ffffec56" />
              <property name="solidity" type="float" value="1.000000" />
              <property name="fill" type="float" value="1.000000" />
              <property name="fade" type="float" value="0.000000" />
              <property name="fadeType" type="int" value="0" />
            </effect>
            <effect id="com.alightcreative.effects.ridges2" locallyApplied="false">
              <property name="color1" type="color" value="#ff292929" />
              <property name="color2" type="color" value="#ffbebebe" />
              <property name="evolution" type="float">
                <kf t="0.000000" v="0.000000" />
                <kf t="0.059540" v="0.850000" />
              </property>
              <property name="octaves" type="float" value="1.000000" />
              <property name="scale" type="float" value="1.650000" />
              <property name="seed" type="float" value="0.040000" />
              <property name="stretch" type="vec2" value="1.000000,0.090000" />
              <property name="intensity" type="float" value="1.000000" />
            </effect>
            <content>T</content>
          </text>
          <text id="370162" label="c" startTime="0" endTime="33843" fillType="color" mediaFillMode="stretch" size="56.000000" font="imported?name=Montserrat-Bold.ttf" wrapWidth="260" align="center">
            <transform>
              <location value="494.296875,360.000000,0.000000" />
              <rotation>
                <kf t="0.000000" v="0.000000" />
              </rotation>
            </transform>
            <fillColor value="#ff7f7f7f" />
            <effect id="com.alightcreative.effects.flip3" locallyApplied="false">
              <property name="angle" type="float">
                <kf t="0.000000" v="48.100002" />
                <kf t="0.059333" v="10.900001" />
              </property>
              <property name="axis" type="float" value="37.000000" />
              <property name="crop" type="float" value="1.000000" />
              <property name="zdist" type="float" value="0.000000" />
              <property name="solid" type="bool" value="false" />
              <property name="solidColor" type="color" value="#ffdd4455" />
              <property name="thickness" type="float" value="1.000000" />
              <property name="enableLight" type="bool" value="false" />
              <property name="lightIntensity" type="float" value="1.000000" />
              <property name="lightColor" type="color" value="#ffffffff" />
              <property name="shine" type="float" value="0.800000" />
              <property name="spec" type="float" value="30.000000" />
              <property name="ambient" type="float" value="0.100000" />
              <property name="lightDir" type="vec2" value="75.000000,-75.000000" />
              <property name="lightDepth" type="float" value="-100.000000" />
            </effect>
            <effect id="com.alightcreative.effects.ridges2" locallyApplied="false">
              <property name="color1" type="color" value="#ff444444" />
              <property name="evolution" type="float">
                <kf t="0.000000" v="0.000000" />
                <kf t="0.059540" v="0.850000" />
              </property>
              <property name="octaves" type="float" value="1.000000" />
              <property name="scale" type="float" value="1.650000" />
              <property name="stretch" type="vec2" value="1.000000,1.000000" />
              <property name="intensity" type="float" value="1.000000" />
              <property name="seed" type="float" value="0.000000" />
              <property name="color2" type="color" value="#ffffffff" />
            </effect>
            <effect id="com.alightcreative.internal.smoothbevel" locallyApplied="false">
              <property name="angle_d" type="float" value="79.000000" />
              <property name="angle_s" type="float" value="118.000000" />
              <property name="elevation_d" type="float" value="1.150000" />
              <property name="elevation_s" type="float" value="5.000000" />
              <property name="intensity_d" type="float" value="0.640000" />
              <property name="radius" type="float" value="8.000000" />
              <property name="spec" type="float" value="49.980000" />
              <property name="color_d" type="color" value="#ffffffff" />
              <property name="color_s" type="color" value="#ffffffff" />
              <property name="intensity_s" type="float" value="1.000000" />
            </effect>
            <content>T</content>
          </text>
        </scene>
      </embedScene>
      <embedScene id="370166" label="Group 2" startTime="0" endTime="75865" fillType="intrinsic" outTime="75865" mediaFillMode="stretch">
        <transform>
          <location value="546.064758,370.658173,0.000000" />
          <pivot value="-52.685547,0.000000" />
        </transform>
        <fillColor value="#ff000000" />
        <scene title="" width="1282" height="722" exportWidth="1920" exportHeight="1080" precompose="dynamicResolution" bgcolor="#00000000" totalTime="15099" fps="60" modifiedTime="0" amver="1002351" ffver="106" am="com.alightcreative.motion/5.0.270.1002578" amplatform="android" retime="off" retimeAdaptFPS="false">
          <text id="370160" label="y" startTime="0" endTime="15099" fillType="color" mediaFillMode="stretch" size="56.000000" font="imported?name=Montserrat-Bold.ttf" wrapWidth="260" align="center">
            <transform>
              <location value="587.314453,360.000000,0.000000" />
            </transform>
            <fillColor value="#ff7f7f7f" />
            <effect id="com.alightcreative.effects.flip3" locallyApplied="false">
              <property name="angle" type="float">
                <kf t="0.000000" v="62.100002" />
                <kf t="0.132989" v="11.300000" />
              </property>
              <property name="axis" type="float" value="4.000000" />
              <property name="crop" type="float" value="1.000000" />
              <property name="zdist" type="float" value="0.000000" />
              <property name="solid" type="bool" value="false" />
              <property name="solidColor" type="color" value="#ffdd4455" />
              <property name="thickness" type="float" value="1.000000" />
              <property name="enableLight" type="bool" value="false" />
              <property name="lightIntensity" type="float" value="1.000000" />
              <property name="lightColor" type="color" value="#ffffffff" />
              <property name="shine" type="float" value="0.800000" />
              <property name="spec" type="float" value="30.000000" />
              <property name="ambient" type="float" value="0.100000" />
              <property name="lightDir" type="vec2" value="75.000000,-75.000000" />
              <property name="lightDepth" type="float" value="-100.0000
